[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/"
healthcheckTimeout = 10

[service]
name = "bichosolto"
port = 80