services:
  # Serviço do frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bicho-solto-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - bicho-solto-network

  # Serviço do backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: bicho-solto-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - API_URL=http://localhost:5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bicho_solto_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - JWT_SECRET=local_development_secret_key
      - JWT_EXPIRES_IN=7d
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=5242880
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - bicho-solto-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5000/api/diagnostico"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Serviço do PostgreSQL
  postgres:
    image: postgres:14
    container_name: bicho-solto-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=bicho_solto_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bicho-solto-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Serviço de administração do PostgreSQL (opcional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: bicho-solto-pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@bischosolto.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - bicho-solto-network

networks:
  bicho-solto-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: 