version: '3.8'

services:
  # Serviço de banco de dados PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: bichosolto-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-bicho_solto_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bichosolto-network

  # Serviço de backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bichosolto-backend
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-bicho_solto_db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-animal_rescue_hub_secret_key}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      UPLOAD_DIR: uploads
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-5242880}
      API_URL: ${API_URL:-http://localhost:5000}
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - bichosolto-network

  # Serviço de frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bichosolto-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bichosolto-network

# Volumes persistentes
volumes:
  postgres_data:
    driver: local

# Redes
networks:
  bichosolto-network:
    driver: bridge 