version: '3.8'

services:
  # Serviço do frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT:-80}:80"
    environment:
      - VITE_API_URL=${API_URL}
    depends_on:
      - backend

  # Serviço do backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - API_URL=${API_URL}
      - DB_HOST=postgres-production-56cd.up.railway.app
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=5242880
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      - railway_uploads:/app/uploads

volumes:
  railway_uploads: