version: '3.8'

services:
  # Serviço do frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: railway-local-frontend
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
      - VITE_API_URL=http://localhost:5001
      - VITE_APP_ENV=production
      - VITE_APP_TITLE=Bicho Solto
    depends_on:
      - backend
    networks:
      - railway-local-network

  # Serviço do backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: railway-local-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
      - API_URL=http://localhost:5001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bicho_solto_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - JWT_SECRET=railway_local_secret_key
      - JWT_EXPIRES_IN=7d
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=5242880
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-AIzaSyC7_3XFwXiqZRICVjloOfO9u-hGD1Ei31k}
    volumes:
      - railway_local_uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - railway-local-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Serviço do PostgreSQL
  postgres:
    image: postgres:14
    container_name: railway-local-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=bicho_solto_db
    volumes:
      - railway_local_postgres_data:/var/lib/postgresql/data
    networks:
      - railway-local-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  railway-local-network:
    driver: bridge

volumes:
  railway_local_uploads:
  railway_local_postgres_data: 