[build]
builder = "NIXPACKS"
nixpacksPlan = { providers = ["node"] }

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[service]
name = "bicho-solto-backend"
