[build]
builder = "NIXPACKS"
nixpacksPlan = { providers = ["node"] }
buildCommand = "npm install"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "bicho-solto-backend"
numReplicas = 1
